### ISSUE TITLE
'Toggle' object has no attribute 'value'

### ISSUE THREAD

**Issue by petermc129** [jsignell/pydata_ann_arbor_2019#1]
Getting the above error when running the cell with: 

`trees_toggle = pn.widgets.Toggle(name='Tree Layer', value=True)
trees_toggle.jslink(trees_p, value='glyph_renderer.visible')

pn.Row(trees_toggle, trees_p)`

The error occurs a few times within notebook 3 and also in 4.

[toggle_value.txt](https://github.com/jsignell/pydata_ann_arbor_2019/files/3069872/toggle_value.txt)

**Comment by jsignell** [comment]
I suspect this is a dependency issue. Can you provide the versions of panel and bokeh?

**Comment by petermc129** [comment]
Yeah, looks like you are correct. They are older versions. 
panel 0.4.0
bokeh 1.0.2
But I am running in the trees env from your environment.yml file.

**Comment by jsignell** [comment]
Hmm. That env should be pinning bokeh and panel. Did you create a new environment using `conda env create --file environment.yml`?

**Comment by petermc129** [comment]
Yep, my bad. I had some environmental variables set up that was grabbing the wrong versions.  Works fine after I got rid of the EVs. Thanks. Also, thank you for the talk. Good stuff.

**Comment by jsignell** [comment]
Great! I'm glad you got it working.
