### ISSUE TITLE
something breaks with geopandas 0.5.0

### ISSUE THREAD

**Issue by josephsmann** [jsignell/pydata_ann_arbor_2019#2]
the cell with 
`NDVI.hvplot(x='x', y='y', crs=crs, datashade=True, cmap='viridis', height=500, width=500).opts(tools=[])`
breaks if you use geopandas 0.5.0. Which is what loads with the current environment.yml file. Geopandas 0.4.1 works fine. 

thought you'd want to know. and, thank you very much for your presentation and this notebook. Tons of super useful methods!

**Comment by jsignell** [comment]
Thanks for letting me know. I will pin to geopandas 0.4.1 for now :)
